# Generated by Django 4.0.3 on 2022-06-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
