# Generated by Django 4.0.3 on 2022-06-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0002_remove_orderitem_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
