# Generated by Django 4.0.3 on 2022-06-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0003_alter_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='user',
            field=models.CharField(max_length=50),
        ),
    ]
