# Generated by Django 3.2 on 2022-06-20 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0004_alter_orderitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(upload_to='img/%m'),
        ),
    ]
