# Generated by Django 3.2 on 2022-05-29 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0003_alter_gallery_description'),
        ('udibaba', '0004_category_product'),
    ]

    operations = [
    ]
