# Generated by Django 3.2 on 2022-05-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0005_merge_20220529_1642'),
        ('udibaba', '0005_merge_20220529_1713'),
    ]

    operations = [
    ]
