# Generated by Django 3.2 on 2022-06-14 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0002_alter_customerprofile_phone'),
        ('udibaba', '0006_alter_orderitem_user'),
    ]

    operations = [
    ]
