# Generated by Django 4.0.5 on 2022-06-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0006_alter_event_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='state',
            field=models.CharField(choices=[('Bagmati Province', 'Bagmati Province')], max_length=50),
        ),
    ]
