# Generated by Django 4.0.5 on 2022-06-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0007_remove_order_zipcode_alter_customerprofile_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zipcode',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
