# Generated by Django 3.2 on 2022-06-14 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0008_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='customer',
        ),
    ]
