# Generated by Django 4.0.3 on 2022-06-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0008_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
