# Generated by Django 4.0.5 on 2022-06-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0008_order_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='zipcode',
            field=models.CharField(default='44600', max_length=150),
        ),
    ]
