# Generated by Django 4.0.5 on 2022-06-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0009_alter_order_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='zipcode',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zipcode',
        ),
    ]
