# Generated by Django 3.2 on 2022-06-22 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0010_remove_customerprofile_zipcode_remove_order_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverycharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deliverycost', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
