# Generated by Django 4.0.5 on 2022-06-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0010_remove_customerprofile_zipcode_remove_order_zipcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverycharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('Deliverycost', models.IntegerField()),
            ],
        ),
    ]
