# Generated by Django 3.2 on 2022-06-22 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0011_auto_20220622_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverycharge',
            name='title',
            field=models.CharField(default='udibaba', max_length=20),
            preserve_default=False,
        ),
    ]
