# Generated by Django 4.0.5 on 2022-06-22 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0012_alter_deliverycharge_deliverycost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deliverycharge',
        ),
    ]
