# Generated by Django 3.2 on 2022-06-22 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0012_deliverycharge_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycharge',
            name='Deliverycost',
            field=models.FloatField(),
        ),
    ]
