# Generated by Django 3.2 on 2022-06-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0013_alter_deliverycharge_deliverycost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverycharge',
            name='title',
            field=models.CharField(default='KTM', max_length=20),
        ),
    ]
