# Generated by Django 3.2 on 2022-06-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0014_alter_deliverycharge_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Info', models.CharField(max_length=50, null=True)),
                ('adimage', models.FileField(blank=True, null=True, upload_to='img/ad')),
                ('addesc', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
