# Generated by Django 4.0.5 on 2022-06-23 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0014_alter_deliverycharge_title'),
        ('udibaba', '0015_alter_customerprofile_phone_alter_order_phone'),
    ]

    operations = [
    ]
