# Generated by Django 3.2 on 2022-06-25 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0015_auto_20220625_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adheader',
            name='Info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adheader',
            name='addesc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Multipleadimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='img/ad')),
                ('prod', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='udibaba.adheader')),
            ],
        ),
    ]
