# Generated by Django 4.0.5 on 2022-06-23 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0016_merge_20220623_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
