# Generated by Django 3.2 on 2022-06-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0016_auto_20220625_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipleadimage',
            name='addesc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
