# Generated by Django 4.0.5 on 2022-06-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0017_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cancelled', 'Cancelled'), ('on the way', 'On The Way'), ('delivered', 'Delivered')], default='Pending', max_length=50),
        ),
    ]
