# Generated by Django 3.2 on 2022-06-25 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0017_multipleadimage_addesc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adheader',
            name='adimage',
        ),
        migrations.AlterField(
            model_name='adheader',
            name='addesc',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
