# Generated by Django 3.2 on 2022-06-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0018_auto_20220625_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='multipleadimage',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
