# Generated by Django 3.2 on 2022-06-26 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0018_alter_order_status'),
        ('udibaba', '0019_multipleadimage_link'),
    ]

    operations = [
    ]
