# Generated by Django 3.2 on 2022-06-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0020_merge_20220626_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliverycharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='KTM', max_length=20)),
                ('Deliverycost', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.FileField(blank=True, null=True, upload_to='img/%m'),
        ),
    ]
