# Generated by Django 4.0.5 on 2022-06-28 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0021_auto_20220627_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleadimage',
            name='images',
            field=models.ImageField(upload_to='img/ad'),
        ),
    ]
