# Generated by Django 3.2 on 2022-07-13 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('udibaba', '0022_alter_multipleadimage_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multiplegalleryimage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='gallery_imgs/')),
                ('gallery', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='udibaba.gallery')),
            ],
        ),
    ]
